name: ci-golang-workflow
on:
  pull_request:                         # Vai chamar a ação sempre que fizer um pull_request na branch develop
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest              # Máquina para rodar a aplicação
    steps:
      - uses: actions/checkout@v2       # Pega os dados do push e baixa na máquina escolhida
      - uses: actions/setup-go@v2       # Esse actions/setup-go é o nome do repositório do Git
        with:
          go-version: 1.15              # Versão do Go
#          go-version: ${{ matrix.go }} # Versão do Go caso tenha strategy Matrix
      - run: go test                    # Comandos que serão executados
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: guimeireles/fc2-CI:latest

    # Versões do Go em que serão testadas a aplicação caso esteja habilitado
#    strategy:
#      matrix:
#        go: [ '1.14','1.15' ]